/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nikola_dragomirovic_shoppinglist_Check */

#ifndef _Included_nikola_dragomirovic_shoppinglist_Check
#define _Included_nikola_dragomirovic_shoppinglist_Check
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nikola_dragomirovic_shoppinglist_Check
 * Method:    check
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jint JNICALL Java_nikola_dragomirovic_shoppinglist_Check_check
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
